<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LaborSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('labores')->insert([
            ['nombre_labor' => 'Cosecha de pencas'],
            ['nombre_labor' => 'Ensacado de pencas'],
            ['nombre_labor' => 'Traslado de pencas'],
            ['nombre_labor' => 'Descarga de Pencas'],
            ['nombre_labor' => 'Reparto de Pencas'],
            ['nombre_labor' => 'Plantación'],
            ['nombre_labor' => 'Replante'],
            ['nombre_labor' => 'Llenada infestadores cartones en infestación'],
            ['nombre_labor' => 'Llenada infestadores tubos en infestación'],
            ['nombre_labor' => 'Llenada infestadores mallita en infestación'],
            ['nombre_labor' => 'Traslado infestadores cartón en infestación'],
            ['nombre_labor' => 'Traslado infestadores tubos en infestación'],
            ['nombre_labor' => 'Traslado infestadores mallita en infestación'],
            ['nombre_labor' => 'Colocación infestadores cartones en infestación'],
            ['nombre_labor' => 'Colocación infestadores tubos en infestación'],
            ['nombre_labor' => 'Colocación infestadores mallita en infestación'],
            ['nombre_labor' => 'Traslado de mallas raschel en infestación'],
            ['nombre_labor' => 'Distribucion de malla raschel en infestación'],
            ['nombre_labor' => 'Colocación malla raschel en infestación'],
            ['nombre_labor' => 'Destapa de malla raschel en infestación'],
            ['nombre_labor' => 'Retiro malla raschel en infestación'],
            ['nombre_labor' => 'Recojo infestadores cartón en infestación'],
            ['nombre_labor' => 'Recojo infestadores tubo en infestación'],
            ['nombre_labor' => 'Recojo infestadores mallita en infestación'],
            ['nombre_labor' => 'Vaciado Infestadores cartón en infestación'],
            ['nombre_labor' => 'Vaciado Infestadores tubo en infestación'],
            ['nombre_labor' => 'Vaciado Infestadores mallita en infestación'],
            ['nombre_labor' => 'Traslado de cajas y/o bolsas vacias para infestadores'],
            ['nombre_labor' => 'Traslado de malla raschel en re-infestación'],
            ['nombre_labor' => 'Distribucion de malla raschel en re-Infestacion'],
            ['nombre_labor' => 'Colocación malla raschel re-infestación'],
            ['nombre_labor' => 'Llenada infestadores cartones en re-infestación'],
            ['nombre_labor' => 'Llenada infestadores tubos en re-infestación'],
            ['nombre_labor' => 'Llenada infestadores mallita en re-infestación'],
            ['nombre_labor' => 'Traslado infestadores cartón en re-infestación'],
            ['nombre_labor' => 'Traslado infestadores tubo en re-infestación'],
            ['nombre_labor' => 'Traslado infestadores mallita en re-infestación'],
            ['nombre_labor' => 'Colocación infestadores en re-infestación cartones'],
            ['nombre_labor' => 'Colocación infestadores en re-infestación tubos'],
            ['nombre_labor' => 'Colocación infestadores en re-infestación mallita'],
            ['nombre_labor' => 'Cosecha mama o pre-cosecha'],
            ['nombre_labor' => 'Retiro y colocación malla raschel en cosecha mama o pre-cosecha'],
            ['nombre_labor' => 'Recojo infestadores re-infestación cartón'],
            ['nombre_labor' => 'Recojo infestadores re-infestación tubo'],
            ['nombre_labor' => 'Recojo infestadores re-infestación mallita'],
            ['nombre_labor' => 'Destapa de malla raschel en re-infestación'],
            ['nombre_labor' => 'Retiro definitivo de malla raschel re-infestación'],
            ['nombre_labor' => 'Vaciado Infestadores cartón en re-infestación'],
            ['nombre_labor' => 'Vaciado Infestadores tubo en re-infestación'],
            ['nombre_labor' => 'Vaciado Infestadores mallita en re-infestación'],
            ['nombre_labor' => 'Traslado de cochinilla madre pesada'],
            ['nombre_labor' => 'Traslado cochinilla cosecha madres o pre-cosecha'],
            ['nombre_labor' => 'Aplicación cebo tóxico'],
            ['nombre_labor' => 'Aplicación sanitaria (mochila)'],
            ['nombre_labor' => 'Aplicación herbicida (mochila)'],
            ['nombre_labor' => 'Control manual quereza'],
            ['nombre_labor' => 'Poda sanitaria'],
            ['nombre_labor' => 'Deshierbo'],
            ['nombre_labor' => 'Desbrote'],
            ['nombre_labor' => 'Eliminación de frutos'],
            ['nombre_labor' => 'Aplicación de estiércol'],
            ['nombre_labor' => 'Retorno a almacen de infestadores vacios (carton, mallita, tubo)'],
            ['nombre_labor' => 'Rastrojeo (junta y quema de rastrojo)'],
            ['nombre_labor' => 'Aporque de pencas Triturada'],
            ['nombre_labor' => 'Pesado fertilizantes'],
            ['nombre_labor' => 'Reparto de fertilizantes'],
            ['nombre_labor' => 'Poda'],
            ['nombre_labor' => 'Traslado cochinilla de cosecha'],
            ['nombre_labor' => 'Post-cosecha (Venteado, extendido y filtrado)'],
            ['nombre_labor' => 'Traslado de infestadores vacios campo a campo'],
            ['nombre_labor' => 'Reparto de cinta'],
            ['nombre_labor' => 'Colocación cinta de riego'],
            ['nombre_labor' => 'Arreglo conectores'],
            ['nombre_labor' => 'Lavado de cinta'],
            ['nombre_labor' => 'Parchado cinta de riego'],
            ['nombre_labor' => 'Amarre terminales cinta de riego'],
            ['nombre_labor' => 'Retiro de cinta de riego del campo'],
            ['nombre_labor' => 'Confeccion infestadores malla'],
            ['nombre_labor' => 'Tractorista'],
            ['nombre_labor' => 'Jardineria'],
            ['nombre_labor' => 'Riego y fertilización'],
            ['nombre_labor' => 'Riego aspersión'],
            ['nombre_labor' => 'Traslado sistema de aspersión'],
            ['nombre_labor' => 'Instalación sistema de aspersión'],
            ['nombre_labor' => 'Desmonte sistema de aspersión'],
            ['nombre_labor' => 'Instalación tubería'],
            ['nombre_labor' => 'Instalación arco de riego'],
            ['nombre_labor' => 'Evaluacion de campo'],
            ['nombre_labor' => 'Asistente de Produccion'],
            ['nombre_labor' => 'Asistente Administrativo campo'],
            ['nombre_labor' => 'Capataz General'],
            ['nombre_labor' => 'Capataz 2'],
            ['nombre_labor' => 'Evaluador de Sanidad'],
            ['nombre_labor' => 'Cocinera'],
            ['nombre_labor' => 'Vigilancia'],
            ['nombre_labor' => 'Vacaciones'],
            ['nombre_labor' => 'Descanso Medico'],
            ['nombre_labor' => 'Atencion medica'],
            ['nombre_labor' => 'Licencias'],
            ['nombre_labor' => 'Cerco perimétrico'],
            ['nombre_labor' => 'Poda-Naranja'],
            ['nombre_labor' => 'Cosecha - Naranja'],
            ['nombre_labor' => 'Eliminación fruta malograda'],
            ['nombre_labor' => 'Aplicaciones sanitarias naranja'],
            ['nombre_labor' => 'Poda de uva'],
            ['nombre_labor' => 'Amarrado de tallo'],
            ['nombre_labor' => 'Raleo de racimos'],
            ['nombre_labor' => 'Raleo de hojas'],
            ['nombre_labor' => 'Cosecha de uva'],
            ['nombre_labor' => 'Aplicación de cianamida'],
            ['nombre_labor' => 'Limpieza acequias'],
            ['nombre_labor' => 'Limpíeza desarenador'],
            ['nombre_labor' => 'Parchado geomembrana'],
            ['nombre_labor' => 'Limpieza estanque (Jornales)'],
            ['nombre_labor' => 'Arreglo almacenes'],
            ['nombre_labor' => 'Recojo de basura'],
            ['nombre_labor' => 'Medición areas'],
            ['nombre_labor' => 'Desatoro de goteros'],
            ['nombre_labor' => 'Lavado de pencas'],
            ['nombre_labor' => 'Labores ensayos'],
            ['nombre_labor' => 'Aplicación manual de estiércol'],
            ['nombre_labor' => 'Mantenimiento de maquinarias'],
            ['nombre_labor' => 'Carga y descarga de fertilizantes'],
            ['nombre_labor' => 'Carga y descarga de Biol'],
            ['nombre_labor' => 'Envasada de biol'],
            ['nombre_labor' => 'Reparto de biol'],
            ['nombre_labor' => 'Preparación de cebo tóxico'],
            ['nombre_labor' => 'Tapado de pencas siembra'],
            ['nombre_labor' => 'Desterrado de pencas-siembra'],
            ['nombre_labor' => 'Desinfección de mondadientes'],
            ['nombre_labor' => 'Cortado de malla para infestadores'],
            ['nombre_labor' => 'Doblado de mallas para infestadores'],
            ['nombre_labor' => 'Traslado personal'],
            ['nombre_labor' => 'Eliminacion manual de aranas'],
            ['nombre_labor' => 'Cambio de mallitas en infestacion'],
            ['nombre_labor' => 'Entresacado de pencas malogradas'],
            ['nombre_labor' => 'Retorno a almacen de infestadores mallita con cochinilla'],
            ['nombre_labor' => 'Raleo de Brotes'],
            ['nombre_labor' => 'Cambio de mallitas en RE infestacion'],
            ['nombre_labor' => 'Mantenimiento de trampas de luz'],
            ['nombre_labor' => 'Tapado de estiercol manual'],
            ['nombre_labor' => 'Mantenimiento de estanque'],
            ['nombre_labor' => 'Mantenimiento de secadero de cochinilla'],
            ['nombre_labor' => 'Trituracion de penca'],
            ['nombre_labor' => 'Aporque'],
            ['nombre_labor' => 'Limpieza de campo'],
        ]);
    }
}
