<?php

namespace Database\Seeders;

use App\Models\PlanTipoAsistencia;
use App\Services\PlanTipoAsistenciaServicio;
use Illuminate\Database\Seeder;

class PlanTipoAsistenciaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(PlanTipoAsistenciaServicio $servicio): void
    {
        $tiposAsistencia = [
            [
                'id' => 1,
                'codigo' => 'A',
                'descripcion' => 'Asistido',
                'horas_jornal' => 8,
                'color' => '#FFFFFF',
                'tipo' => 'ASISTENCIA',
                'afecta_sueldo' => 1,
                'porcentaje_remunerado' => 100.00,
                'requiere_documento' => 0,
                'acumula_vacaciones' => 1,
                'acumula_asistencia' => 1,
                'activo' => 1,
                'created_at' => '2025-10-17 14:24:39',
                'updated_at' => '2025-10-17 14:24:39',
            ],
            [
                'id' => 2,
                'codigo' => 'F',
                'descripcion' => 'Falta',
                'horas_jornal' => 0,
                'color' => '#DA9694',
                'tipo' => 'ASISTENCIA',
                'afecta_sueldo' => 1,
                'porcentaje_remunerado' => 0.00,
                'requiere_documento' => 0,
                'acumula_vacaciones' => 0,
                'acumula_asistencia' => 0,
                'activo' => 1,
                'created_at' => '2025-10-17 14:24:39',
                'updated_at' => '2025-10-17 14:24:39',
            ],
            [
                'id' => 3,
                'codigo' => 'V',
                'descripcion' => 'Vacaciones',
                'horas_jornal' => 8,
                'color' => '#92CDDC',
                'tipo' => 'VACACIONES',
                'afecta_sueldo' => 0,
                'porcentaje_remunerado' => 100.00,
                'requiere_documento' => 0,
                'acumula_vacaciones' => 0,
                'acumula_asistencia' => 1,
                'activo' => 1,
                'created_at' => '2025-10-17 14:24:39',
                'updated_at' => '2025-10-17 14:24:39',
            ],
            [
                'id' => 4,
                'codigo' => 'LM',
                'descripcion' => 'Licencia Maternidad',
                'horas_jornal' => 0,
                'color' => '#FFC0CB',
                'tipo' => 'LICENCIA',
                'afecta_sueldo' => 0,
                'porcentaje_remunerado' => 100.00,
                'requiere_documento' => 1,
                'acumula_vacaciones' => 1,
                'acumula_asistencia' => 1,
                'activo' => 1,
                'created_at' => '2025-10-17 14:24:39',
                'updated_at' => '2025-10-17 14:24:39',
            ],
            [
                'id' => 5,
                'codigo' => 'LSG',
                'descripcion' => 'Licencia Sin Goce',
                'horas_jornal' => 0,
                'color' => '#FFFF00',
                'tipo' => 'LICENCIA',
                'afecta_sueldo' => 1,
                'porcentaje_remunerado' => 0.00,
                'requiere_documento' => 1,
                'acumula_vacaciones' => 0,
                'acumula_asistencia' => 1,
                'activo' => 1,
                'created_at' => '2025-10-17 14:24:39',
                'updated_at' => '2026-02-12 20:47:44',
            ],
            [
                'id' => 6,
                'codigo' => 'LCG',
                'descripcion' => 'Licencia Con Goce',
                'horas_jornal' => 8,
                'color' => '#FFFF00',
                'tipo' => 'LICENCIA',
                'afecta_sueldo' => 0,
                'porcentaje_remunerado' => 100.00,
                'requiere_documento' => 1,
                'acumula_vacaciones' => 1,
                'acumula_asistencia' => 1,
                'activo' => 1,
                'created_at' => '2025-10-17 14:24:39',
                'updated_at' => '2025-10-17 14:24:39',
            ],
            [
                'id' => 7,
                'codigo' => 'DM',
                'descripcion' => 'Descanso Médico',
                'horas_jornal' => 8,
                'color' => '#FABF8F',
                'tipo' => 'PERMISO',
                'afecta_sueldo' => 0,
                'porcentaje_remunerado' => 100.00,
                'requiere_documento' => 1,
                'acumula_vacaciones' => 1,
                'acumula_asistencia' => 1,
                'activo' => 1,
                'created_at' => '2025-10-17 14:24:39',
                'updated_at' => '2025-10-17 14:24:39',
            ],
            [
                'id' => 8,
                'codigo' => 'AM',
                'descripcion' => 'Atención Médica',
                'horas_jornal' => 8,
                'color' => '#C4D79B',
                'tipo' => 'PERMISO',
                'afecta_sueldo' => 0,
                'porcentaje_remunerado' => 100.00,
                'requiere_documento' => 0,
                'acumula_vacaciones' => 1,
                'acumula_asistencia' => 1,
                'activo' => 1,
                'created_at' => '2025-10-17 14:24:39',
                'updated_at' => '2025-10-17 14:24:39',
            ],
            [
                'id' => 9,
                'codigo' => 'R',
                'descripcion' => 'RENUNCIA',
                'horas_jornal' => 0,
                'color' => '#05DF72',
                'tipo' => 'ASISTENCIA',
                'afecta_sueldo' => 1,
                'porcentaje_remunerado' => 100.00,
                'requiere_documento' => 0,
                'acumula_vacaciones' => 0,
                'acumula_asistencia' => 0,
                'activo' => 1,
                'created_at' => '2026-06-25 20:52:53',
                'updated_at' => '2026-06-25 20:52:53',
            ],
            [
                'id' => 11,
                'codigo' => 'FR',
                'descripcion' => 'FERIADO',
                'horas_jornal' => 0,
                'color' => '#ffffff',
                'tipo' => 'ASISTENCIA',
                'afecta_sueldo' => 1,
                'porcentaje_remunerado' => 100.00,
                'requiere_documento' => 0,
                'acumula_vacaciones' => 0,
                'acumula_asistencia' => 1,
                'activo' => 1,
                'created_at' => '2026-08-25 12:57:02',
                'updated_at' => '2026-08-25 12:57:02',
            ],
        ];

        foreach ($tiposAsistencia as $tipo) {
            PlanTipoAsistencia::create($tipo);
        }

    }
}
